"""Calculation module: core/formula.py holds the mathematics and, below it, the solver."""

from general.plotting import Viewport, fit_viewport, nice_step

from .formula import (
    QuadraticSolution,
    axis_of_symmetry,
    axis_x,
    curve_points,
    direction,
    discriminant,
    evaluate,
    factored_form,
    factored_form_text,
    fmt,
    intercept_points,
    opens,
    parabola,
    plot_window,
    quadratic_formula,
    root_nature,
    roots,
    solve,
    solve_linear,
    standard_form_text,
    vertex,
    vertex_form,
    vertex_form_text,
    vertex_point,
    x_intercepts,
    y_intercept,
    y_intercept_point,
)

__all__ = [
    "QuadraticSolution",
    "Viewport",
    "axis_of_symmetry",
    "axis_x",
    "curve_points",
    "direction",
    "discriminant",
    "evaluate",
    "factored_form",
    "factored_form_text",
    "fit_viewport",
    "fmt",
    "intercept_points",
    "nice_step",
    "opens",
    "parabola",
    "plot_window",
    "quadratic_formula",
    "root_nature",
    "roots",
    "solve",
    "solve_linear",
    "standard_form_text",
    "vertex",
    "vertex_form",
    "vertex_form_text",
    "vertex_point",
    "x_intercepts",
    "y_intercept",
    "y_intercept_point",
]
